/** Shared honest-scope language for screening results (app + PDF). */

export const SCREENING_DISCLAIMER_TITLE = "Screening risk score — not a diagnosis";

export const SCREENING_DISCLAIMER_SCOPE =
  "TBhon shows a staff-operated screening risk score from checklist answers, cough audio, and sputum smear signals when captured. It is not a medical diagnosis and must not be used alone to confirm or exclude TB.";

export const SCREENING_DISCLAIMER_LIMITS =
  "Cough analysis cannot rule TB in or out with certainty, and this tool cannot detect or exclude all lung diseases or other conditions. Standard clinical evaluation and laboratory testing are required for diagnosis and treatment decisions.";

export const SCREENING_FUSION_METHOD_NOTE =
  "Weighted log-odds fusion of checklist, cough ML, and sputum ML — screening risk score only, not a diagnosis.";

export const SCREENING_PDF_MEDIA_NOTE =
  "Cough audio replay and sputum image analysis feedback are available only inside the TBhon app and are not included in this PDF export.";

export const SCREENING_PDF_FOOTER = "Generated by TBhon · Screening support only — not a diagnosis";

/** Staff referral guidance when risk is moderate or high. */
export const SCREENING_STAFF_REFERRAL_LINE = "Refer for GeneXpert / smear / clinical workup";
